### ISSUE TITLE
Lazer\Classes\mb_strtolower()

### ISSUE THREAD

**Issue by Jtreix** [Greg0/Lazer-Database#38]
What is the cause of this error;

`PHP Fatal error:  Call to undefined function Lazer\Classes\mb_strtolower() in /home/mainsite/project/app/vendor/greg0/lazer-database/src/Classes/Database.php on line 537`

**Comment by Jtreix** [comment]
Error Log;
```
[28-Jun-2018 09:43:46 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(553) : eval()'d code:1
Stack trace:
#0 /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(553): eval()
#1 [internal function]: Lazer\Classes\Database->Lazer\Classes\{closure}(Object(stdClass))
#2 /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(557): array_filter(Array, Object(Closure))
#3 [internal function]: Lazer\Classes\Database->wherePending()
#4 /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(223): call_user_func(Array)
#5 /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(894): Lazer\Classes\Database->pending()
#6 /home/bizkodlayalim/project/app/views/partials/head.php(4): Lazer\Classes\Database->findAll()
#7 /home/bizkodlayalim/project/app/core/page.php(66): require_once('/home/bizkodlay...')
#8 /home/bizkodlayalim/pro in /home/bizkodlayalim/project/app/vendor/greg0/lazer-database/src/Classes/Database.php(553) : eval()'d code on line 1
```

head.php(4)

`$menus = DB::table('menus')->where('sub', '=', 0)->findAll();`

page.php(66)

`require_once(DIR.'/app/views/partials/head.php');`

**Comment by Greg0** [comment]
If you can't install/enable extenstions on your system/server you can install polyfill library for that:
https://github.com/symfony/polyfill-mbstring

**Comment by Jtreix** [comment]
Thanks this extensions installed but its not working this error source is vps php version.
